<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Spin.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Spin.ico" />
    <None Remove="Resources\tick.wav" />
    <None Remove="Spin.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Spin.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Spin.ico" />
    <Resource Include="Resources\tick.wav" />
    <Resource Include="Spin.ico" />
  </ItemGroup>

</Project>
